config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'welcome/index'

  resources :maps
  resources :players do
    resources :matches
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map.rb
class Map < ApplicationRecord
  has_many :matches, dependent: :destroy

  validates :name, presence: true
  validates :exhibition_name, presence: true
  validates :map_type, presence: true
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :player
  belongs_to :map
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :matches, dependent: :destroy

  validates :name, presence: true
  validates :age, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def show
    @map = Map.find(params[:id])
  end

  def index
    @maps = Map.all
  end

  def new
    @map = Map.new
  end

  def create
    @map = Map.new(map_params)

    if @map.save
      redirect_to @map
    else
      render action: 'new'
    end
  end

  def edit
    @map = Map.find(params[:id])
  end

  def update
    @map = Map.find(params[:id])

    if @map.update(map_params)
      redirect_to @map
    else
      render 'edit'
    end
  end

  def destroy
    @map = Map.find(params[:id])
    @map.destroy

    redirect_to maps_path
  end

  private
    def map_params
      params.require(:map).permit(:name, :exhibition_name, :map_type)
    end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def new
    @player = Player.find(params[:player_id])
    @maps = Map.all
    @match = Match.new
  end

  def create
    @player = Player.find(params[:player_id])
    @map = Map.find(params[:match][:map])

    @player.matches.create(matches_params.merge(map: @map))
    redirect_to player_path(@player)
  end

  def destroy
    player = Player.find(params[:player_id])
    player.matches.find(params[:id]).destroy

    redirect_to player_path(player)
  end

  private

    def matches_params
      params.require(:match).permit(:kills, :assists, :deaths)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new
    @player = Player.new
  end

  def show
    @player = Player.find(params[:id])
  end

  def index
    @players = Player.all
  end

  def edit
    @player = Player.find(params[:id])
  end

  def create
    @player = Player.new(player_params)

    if @player.save
      redirect_to @player
    else
      render action: 'new'
    end
  end

  def update
    @player = Player.find(params[:id])

    if @player.update(player_params)
      redirect_to @player
    else
      render action: 'edit'
    end
  end

  def destroy
    Player.find(params[:id]).destroy

    redirect_to players_path
  end

  private
    def player_params
      params.require(:player).permit(:name, :age)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CsLog</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.5.3/css/bulma.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item" href="/">
            <h2 class="is-size-4">CSLogs</h2>
          </a>

          <button class="button navbar-burger">
            <span></span>
            <span></span>
            <span></span>
          </button>
        </div>

        <div class="navbar-menu">
          <div class="navbar-start">
            <%= link_to 'Maps', maps_path, class: 'navbar-item' %>
            <%= link_to 'Players', players_path, class: 'navbar-item' %>

          </div>
        </div>
      </div>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/maps/_form.html.erb
<%= form_with model: @map, local: true do |form| %>
  <div class="field">
    <%= form.label :name, 'Name', class: 'label' %>
    <div class="control"><%= form.text_field :name, class: 'input' %></div>
    <% if @map.errors[:name] %>
      <p class="help is-danger"><%=@map.errors[:name].first %></p>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :exhibition_name, 'Exhibition Name', class: 'label' %>
    <div class="control">
      <%= form.text_field :exhibition_name, class: 'input' %>
    </div>
    <% if @map.errors[:exhibition_name] %>
      <p class="help is-danger"><%=@map.errors[:exhibition_name].first %></p>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :map_type, 'Map type', class: 'label' %>
    <div class="control">
      <div class="select">
        <%= form.select(:map_type, options_for_select([['Bomb Defusal', 1], ['Hostage Rescue', 2]])) %>
      </div>
    </div>
    <% if @map.errors[:map_type] %>
      <p class="help is-danger"><%=@map.errors[:map_type].first %></p>
    <% end %>
  </div>

  <div class="field">
    <div class="control">
      <%= form.submit nil, class: 'button is-primary' %>
    </div>
  </div>
<% end %>

app/views/maps/edit.html.erb
<nav class="breadcrumb" aria-label="breadcrumbs">
  <div class="container">
    <ul>
      <li><a href="/">Home</a></li>
      <li><%= link_to 'Maps', maps_path %></li>
      <li><%= link_to @map.exhibition_name, map_path(@map) %></li>
      <li class="is-active"><a href="#" aria-current="page">Edit</a></li>
    </ul>
  </div>
</nav>

<div class="container">
  <h1 class="is-size-2 has-text-weight-light">Edit Map: <%= @map.exhibition_name %></h1>

  <div class="columns">
    <div class="column is-3">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/maps/index.html.erb
<nav class="breadcrumb" aria-label="breadcrumbs">
  <div class="container">
    <ul>
      <li><a href="/">Home</a></li>
      <li class="is-active"><a href="#" aria-current="page">Maps</a></li>
    </ul>
  </div>
</nav>

<div class="container">
  <div class="is-flex" style="align-items: center; justify-content: space-between">
      <h1 class="is-size-2 has-text-weight-light" >Maps</h1>
      <%= link_to 'Add a new map', new_map_path, class: 'button is-pulled-right' %>
  </div>

  <br>

  <table class="table is-fullwidth">
    <thead class="is-primary">
      <tr>
        <th>Name</th>
        <th>Exhibition Name</th>
        <th>Map Type</th>
        <th class="has-text-right">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @maps.each do |map| %>
      <tr>
        <td><%= map.name %></td>
        <td><%= map.exhibition_name %></td>
        <td><%= map.map_type %></td>
        <td class="has-text-right">
          <%= link_to 'Show', map_path(map) %> |
          <%= link_to 'Edit', edit_map_path(map) %> |
          <%= link_to 'Destroy', map_path(map), method: :delete, data: {confirm: 'Are you sure?'} %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/maps/new.html.erb
<nav class="breadcrumb" aria-label="breadcrumbs">
  <div class="container">
    <ul>
      <li><a href="/">Home</a></li>
      <li><%= link_to 'Maps', maps_path %></li>
      <li class="is-active"><a href="#" aria-current="page">New Map</a></li>
    </ul>
  </div>
</nav>

<div class="container">
  <h1 class="is-size-2 has-text-weight-light">Add a new map</h1>

  <div class="columns">
    <div class="column is-3">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/maps/show.html.erb
<nav class="breadcrumb" aria-label="breadcrumbs">
  <div class="container">
    <ul>
      <li><a href="/">Home</a></li>
      <li><%= link_to 'Maps', maps_path %></li>
      <li class="is-active"><a href="#" aria-current="page"><%= @map.exhibition_name %></a></li>
    </ul>
  </div>
</nav>

<div class="container">
  <div class="is-flex" style="align-items: center">
    <h1 class="is-size-2 has-text-weight-light">
      <%= @map.exhibition_name %>
    </h1>
    &nbsp;&nbsp;
    <%= link_to 'Edit', edit_map_path(@map), class: 'button' %>
  </div>

  <table class="table">
    <tr>
      <th>Map Name</th>
      <td><%= @map.name %></td>
    </tr>

    <tr>
      <th>Exhibition Name</th>
      <td><%= @map.exhibition_name %></td>
    </tr>

    <tr>
      <th>Map Type</th>
      <td><%= @map.map_type %></td>
    </tr>
  </table>
</div>

app/views/matches/_matches.html.erb
<table>
  <thead>
    <tr>
      <th>Map</th>
      <th>Kills</th>
      <th>Assists</th>
      <th>Deaths</th>
      <th>KDA</th>
      <th></th>
    </tr>
  </thead>
  <% @player.matches.each do |match| %>
    <tr>
      <td><%= match.map.exhibition_name %></td>
      <td><%= match.kills %></td>
      <td><%= match.assists %></td>
      <td><%= match.deaths %></td>
      <td>
        <% if match.deaths > 0 %>
          <%= number_to_percentage (match.kills + match.assists) / match.deaths.to_f, precision: 2 %>
        <% else %>
          <%= number_to_percentage match.kills + match.assists, precision: 2 %>
        <% end %>
      </td>
      <td>
        <%= link_to 'Delete Match', player_match_path(@player, match), method: :delete, data: {confirm: 'Are you sure?'} %>
      </td>
    </tr>
  <% end %>
</table>

app/views/matches/new.html.erb
<h1>Add a match result for player <%= @player.name %></h1>

<%= link_to 'Back to player', player_path(@player) %>

<%= form_with model: [@player, @player.matches.build], local: true do |form| %>
  <p>
    <%= form.label :kills %>
    <%= form.number_field :kills, min: 0, value: 0 %>
  </p>

  <p>
    <%=  form.label :assists %>
    <%= form.number_field :assists, min: 0, value: 0 %>
  </p>

  <p>
    <%= form.label :deaths %>
    <%= form.number_field :deaths, min: 0, value: 0 %>
  </p>

  <p>
    <%= form.label :map %>
    <%= form.select :map,
      options_from_collection_for_select(@maps, :id, :exhibition_name),
      include_blank: "Select a map"
    %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/players/_form.html.erb
<%= form_with model: @player, local:true do |form| %>

  <% if @player.errors.any? %>
  <div>
    <h3>
      <%= pluralize(@player.errors.count, 'error') %> prohibited this map from being saved:
    </h3>

    <ul>
    <% @player.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :age %><br>
    <%= form.number_field :age, in: 1..99%>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/players/edit.html.erb
<h1>Edit Player: <%= @player.name %></h1>

<%= link_to 'Back', players_path %>

<%= render 'form' %>

app/views/players/index.html.erb
<h1>Players</h1>

<%= link_to 'New', new_player_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th></th>
    </tr>
  </thead>
  <% @players.each do |player| %>
  <tr>
    <td><%= player.name %></td>
    <td><%= player.age %></td>
    <td>
      <%= link_to 'Show', player_path(player) %> |
      <%= link_to 'Edit', edit_player_path(player) %> |
      <%= link_to 'Delete', player_path(player), method: :delete, data: {confirm: 'Are you sure?'} %>
    </td>
  </tr>
  <% end %>
</table>

app/views/players/new.html.erb
<h1>Create a new Player</h1>

<%= link_to 'Back', players_path %>

<%= render 'form' %>

app/views/players/show.html.erb
<h1><%= @player.name %></h1>

<%= link_to 'Back', players_path %> |
<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Add a match result', new_player_match_path(@player) %>

<p>
  <strong>Age:</strong> <%= @player.age %>
</p>

<hr>
<h2>Matches</h2>

<% if @player.matches.count > 0 %>
  <%= render 'matches/matches' %>
<% else %>
  No matches for this player
<% end %>

app/views/welcome/index.html.erb
<h1>Cs Logs</h1>

<%= link_to 'Maps', controller: 'maps' %>